title:              ADAtastory
email:              paul.cadetdefontenay@epfl.ch
description:        A Datastory about women representation in the movie industry
author:             NoNansLand

url:                "https://pauldfepfl.github.io"

# Social Profiles
twitter_username:   
github_username:    Pauldfepfl
facebook_username:  
instagram_username:  
linkedin_username:


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
